quarkus.application.name=notification-service
quarkus.http.port=8083

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=traceflow
quarkus.datasource.password=traceflow
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/notification

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.info-title=TraceFlow Notification API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.always-include=true

mp.messaging.incoming.inspection-failed-in.connector=smallrye-kafka
mp.messaging.incoming.inspection-failed-in.topic=inspection.failed
mp.messaging.incoming.inspection-failed-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.inspection-failed-in.auto.offset.reset=earliest
mp.messaging.incoming.inspection-failed-in.group.id=notification-service

mp.messaging.outgoing.dead-letter-out.connector=smallrye-kafka
mp.messaging.outgoing.dead-letter-out.topic=traceflow.dlq
mp.messaging.outgoing.dead-letter-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=localhost:9092

quarkus.container-image.group=traceflow
quarkus.container-image.name=notification-service
quarkus.container-image.tag=1.0.0

%test.quarkus.devservices.enabled=false
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.kafka.devservices.enabled=false
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:notification;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.flyway.enabled=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.mp.messaging.incoming.inspection-failed-in.connector=smallrye-in-memory
%test.mp.messaging.outgoing.dead-letter-out.connector=smallrye-in-memory
%test.quarkus.scheduler.enabled=false
